global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true

route:
  receiver: Default
  group_by:
    - alertname
  continue: false
  routes:
    - receiver: Default
      matchers:
        - severity="high"
      continue: false
  group_wait: 15s
  group_interval: 15s
  repeat_interval: 1m

receivers:
  - name: Default
    webhook_configs:
      - send_resolved: true
        http_config:
          follow_redirects: true
        url: http://node_app:4000/alerts
        max_alerts: 0

templates: []
